[theme]
primaryColor = "#EF4444"
backgroundColor = "#e5e2fd"
secondaryBackgroundColor = "#c7c7c7ff"
textColor = "#0c0c0cff"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"

[browser]
gatherUsageStats = false
